efficient async formatting
replit/pyright-extended pull request #25
Opened 2023-11-09 22:52 UTC by noneofyourbusiness1415252

Prevent spawning new processes for each format.
Initial plan was to also replace `yapf` with [a monkey-patch of `black`](https://github.com/noneofyourbusiness1415252/black) but for now this is an easy way

2023-11-12 15:48 UTC, noneofyourbusiness1415252 commented
I've put this fork into [a template](https://replit.com/@UMARismyname/ruff#main.py) -- except I realised that the pyright-extended used in repls is actually outdated and uses an old version of `ruff` from the Nix cache, so I had to modify the `pyright-langserver.js` to reverse the effect of https://github.com/replit/pyright-extended/commit/9520facd598a9971d6527623f3f22177de5dd474.

2023-11-24 07:14 UTC, jackyzha0 commented
Hey! Thanks for the contribution. Can we split this into two PRs?

1. Respect formatting (the one in `packages/pyright-internal/src/languageServerBase.ts`)
2. Switch to `ruff` via the WASM module. For this second PR, benchmarks would be nice to see

We also looked at two internally but didn't find a way to pass config in via flags but using WASM is a nice way to get around that! Feel free to ping me for a review once you do that :)

2023-11-24 19:34 UTC, noneofyourbusiness1415252 commented
@jackyzha0 not sure how to go about splitting it up: adding tab support in `pyright-yapf/index.ts` differs between using `yapf` and `ruff`. So I just made a PR from https://github.com/replit/pyright-extended/pull/25/commits/68c5e44b66dc2e84b37b8e0fdab07b412ca91ab1. And then do you want me to split that up so that there's one PR for respecting indent type preference, and one for the performance improvements?
As for benchmarks, all I can say is that, looking at the `?debug=1` lsp logs, the slowest cases were in [the optimised `yapf` version](https://github.com/replit/pyright-extended/pull/25/commits/68c5e44b66dc2e84b37b8e0fdab07b412ca91ab1), and the fastest cases were in `ruff`, formatting the same file multiple times on a Core plan repl. `ruff` maxed at 103ms, and worst case was 3404ms while I held Ctrl+S, spamming formatting requests. I've yet to retrieve similar stats for `yapf` soon.
![image](https://github.com/replit/pyright-extended/assets/80610051/dae596f6-3808-4ee0-8c1c-d4b985d352d8)

2023-11-24 19:41 UTC, jackyzha0 commented
For the first part, I'm looking for just a PR to edit the CLI flags passed to yapf to respect tabs _without_ all the WASM-ed module stuff. As for optimized yapf vs ruff, let's just go with Ruff and I can review that one separately (this should also include the tab formatting option that the first PR includes but for ruff)

The reason is that it'll likely take a few rounds of back and forth to while we review the latter PR but I think it's important to get a working patch in for tab formatting.

2023-11-24 20:01 UTC, noneofyourbusiness1415252 commented
> the WASM-ed module stuff

to be clear, you mean the napi->cpython FFI stuff?

2023-11-24 20:08 UTC, jackyzha0 commented
I don't see any usages of napi ffi in your PR, just `@wasm-fmt/ruff_fmt"` and the header patching for fetching the wasm?

2023-11-24 20:13 UTC, noneofyourbusiness1415252 commented
by that I mean the use of `node-calls-python` in https://github.com/replit/pyright-extended/commit/68c5e44b66dc2e84b37b8e0fdab07b412ca91ab1 for `yapf`

2023-11-30 20:39 UTC, jackyzha0 reviewed
theres a lot of package changes (esp at the root level), can you make sure your package-lock changes are scoped to your changes?

2023-12-02 16:46 UTC, noneofyourbusiness1415252 commented on packages/pyright/langserver.index.js
> +global.fetch = async function(url) {
> theres a lot of package changes 

right, next I'll amend the commit using the original 5 `package-lock.json`s and
```bash
npm run install:all

```

2024-03-16 00:29 UTC, blast-hardcheese commented
Hey there! In an effort to get some confidence around changes like this I added some LSP tests in #32 and #33 which cover completion, linting, and formatting.

I know this PR has been languishing for a while, but I think there's actually either a bug in the upstream `ruff` wrapper, or a bug in how we're loading the WASM bundle:

```shell
$ mkdir python_workspace
$ echo 'print("hello")' > python_workspace/main.py
$ node packages/pyright/dist/pyright.js ./python_workspace/
.../python_workspace/main.py
  .../python_workspace/main.py:1:1 - error: "print" is not defined (pyright[reportUndefinedVariable])
1 error, 0 warnings, 0 informations 
```

Additionally, in order to test this PR I had to delete
```
                {
                    test: /\.wasm$/,
                    type: 'asset/inline',
                },
```
from `webpack.config.js`, since if that's in there I get `TypeError: The URL must be of scheme file`, since the entire wasm file gets inlined as `data:...`, then passed into [`fs.readFile`](https://github.com/wasm-fmt/ruff_fmt/blob/ceda12cdb4cc0ced2643e73165872cc498c3fdf9/crates/ruff_fmt/extra/ruff_fmt_node.js#L6) in recent versions of `ruff_fmt`. Just an FYI in case you rebase this and try to build.

To run the new test suite, `make build test`.

2024-03-16 00:32 UTC, blast-hardcheese requested changes
I think this is moving in the right direction, but it can't be merged as is unfortunately. Going to mark this as "Request changes," but I'm also happy to either close this out due to the upstream bug(s?) or just switch to invoking `ruff` on the CLI instead of using the WASM bundle.

Please just let me know how you'd like to proceed, I'd like to get this in!

2024-03-20 22:45 UTC, noneofyourbusiness1415252 commented
I'd got rid of the `ruff_fmt` package on my end (and even the `ruff` CLI for `ruff check`) [in favour of `ruff_wasm`](https://github.com/replit/nixmodules/commit/d5ddcff9419456ecf54d2582c4b1cc4242198ac0#r138016122), but I have yet to create a build script, and I've now got bigger priorities + a clumsy routine. I don't even know whether it works right now.

2024-04-21 09:42 UTC, rob32 commented
ruff as formatter would be really great. are there any news on this?

2024-04-21 11:32 UTC, noneofyourbusiness1415252 commented
Try [my template](https://replit.com/@UMARismyname/ruff#main.py). To keep the repl updated properly with the latest features from the replit python module, `ruff` would have to go directly in pyright-extended, hence this PR. (an alternative would be to patch the latest version of the replit module to use `ruff` similarly to https://replit.com/@UMARismyname/black?v=1#.config/bashrc, but that would be hard to implement especially if you're going for optimal formatting performance).
As you can see above, there are some upstream issues which mean that I have to rely on patching the `ruff_wasm` crate instead of simply using the `ruff_fmt` npm package. I happened to have already started this in the pyright-extended folder @ https://replit.com/@UMARismyname/black#pyright-extended/.git/hooks/post-merge while I was trying to optimise the linting. I've lost interest in programming on replit, so feel free to try and complete the work.

2025-02-06 17:58 UTC, closed without merging